provider: random
major-version: 4
makeTemplate: bridged
team: ecosystem
license:
    ignore:
        - github.com/terraform-providers/terraform-provider-random/shim
pulumiConvert: 1
registryDocs: true
releaseVerification:
    nodejs: examples/simple/ts
    python: examples/simple/py
    dotnet: examples/simple/csharp
    go: examples/simple/go
integrationTestProvider: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
