[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "ellismg/rollback-importers"

[[constraint]]
  branch = "master"
  name = "github.com/terraform-providers/terraform-provider-random"
