// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package random

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-random/sdk/v4/go/random/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The resource `RandomUuid7` generates a random version 7 uuid string that is intended to be used as a unique identifier for other resources.
//
// This resource uses [google/uuid](https://github.com/google/uuid) to generate a valid V7 UUID for use with services needing a unique string identifier.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-azurerm/sdk/go/azurerm"
//	"github.com/pulumi/pulumi-random/sdk/v4/go/random"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// The following example shows how to generate a unique name for an Azure Resource Group.
//			test, err := random.NewRandomUuid7(ctx, "test", nil)
//			if err != nil {
//				return err
//			}
//			_, err = azurerm.NewResourceGroup(ctx, "test", &azurerm.ResourceGroupArgs{
//				Name:     pulumi.Sprintf("%v-rg", test.Result),
//				Location: "Central US",
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The `pulumi import` command can be used, for example:
//
// Random UUID's can be imported. This can be used to replace a config
// value with a value interpolated from the random provider without
// experiencing diffs.
//
// ```sh
// $ pulumi import random:index/randomUuid7:RandomUuid7 main 0197ad85-fe6e-7e92-a2f5-7550daa83030
// ```
type RandomUuid7 struct {
	pulumi.CustomResourceState

	// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
	Keepers pulumi.StringMapOutput `pulumi:"keepers"`
	// The generated uuid presented in string format.
	Result pulumi.StringOutput `pulumi:"result"`
}

// NewRandomUuid7 registers a new resource with the given unique name, arguments, and options.
func NewRandomUuid7(ctx *pulumi.Context,
	name string, args *RandomUuid7Args, opts ...pulumi.ResourceOption) (*RandomUuid7, error) {
	if args == nil {
		args = &RandomUuid7Args{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RandomUuid7
	err := ctx.RegisterResource("random:index/randomUuid7:RandomUuid7", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRandomUuid7 gets an existing RandomUuid7 resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRandomUuid7(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RandomUuid7State, opts ...pulumi.ResourceOption) (*RandomUuid7, error) {
	var resource RandomUuid7
	err := ctx.ReadResource("random:index/randomUuid7:RandomUuid7", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RandomUuid7 resources.
type randomUuid7State struct {
	// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
	Keepers map[string]string `pulumi:"keepers"`
	// The generated uuid presented in string format.
	Result *string `pulumi:"result"`
}

type RandomUuid7State struct {
	// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
	Keepers pulumi.StringMapInput
	// The generated uuid presented in string format.
	Result pulumi.StringPtrInput
}

func (RandomUuid7State) ElementType() reflect.Type {
	return reflect.TypeOf((*randomUuid7State)(nil)).Elem()
}

type randomUuid7Args struct {
	// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
	Keepers map[string]string `pulumi:"keepers"`
}

// The set of arguments for constructing a RandomUuid7 resource.
type RandomUuid7Args struct {
	// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
	Keepers pulumi.StringMapInput
}

func (RandomUuid7Args) ElementType() reflect.Type {
	return reflect.TypeOf((*randomUuid7Args)(nil)).Elem()
}

type RandomUuid7Input interface {
	pulumi.Input

	ToRandomUuid7Output() RandomUuid7Output
	ToRandomUuid7OutputWithContext(ctx context.Context) RandomUuid7Output
}

func (*RandomUuid7) ElementType() reflect.Type {
	return reflect.TypeOf((**RandomUuid7)(nil)).Elem()
}

func (i *RandomUuid7) ToRandomUuid7Output() RandomUuid7Output {
	return i.ToRandomUuid7OutputWithContext(context.Background())
}

func (i *RandomUuid7) ToRandomUuid7OutputWithContext(ctx context.Context) RandomUuid7Output {
	return pulumi.ToOutputWithContext(ctx, i).(RandomUuid7Output)
}

// RandomUuid7ArrayInput is an input type that accepts RandomUuid7Array and RandomUuid7ArrayOutput values.
// You can construct a concrete instance of `RandomUuid7ArrayInput` via:
//
//	RandomUuid7Array{ RandomUuid7Args{...} }
type RandomUuid7ArrayInput interface {
	pulumi.Input

	ToRandomUuid7ArrayOutput() RandomUuid7ArrayOutput
	ToRandomUuid7ArrayOutputWithContext(context.Context) RandomUuid7ArrayOutput
}

type RandomUuid7Array []RandomUuid7Input

func (RandomUuid7Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RandomUuid7)(nil)).Elem()
}

func (i RandomUuid7Array) ToRandomUuid7ArrayOutput() RandomUuid7ArrayOutput {
	return i.ToRandomUuid7ArrayOutputWithContext(context.Background())
}

func (i RandomUuid7Array) ToRandomUuid7ArrayOutputWithContext(ctx context.Context) RandomUuid7ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RandomUuid7ArrayOutput)
}

// RandomUuid7MapInput is an input type that accepts RandomUuid7Map and RandomUuid7MapOutput values.
// You can construct a concrete instance of `RandomUuid7MapInput` via:
//
//	RandomUuid7Map{ "key": RandomUuid7Args{...} }
type RandomUuid7MapInput interface {
	pulumi.Input

	ToRandomUuid7MapOutput() RandomUuid7MapOutput
	ToRandomUuid7MapOutputWithContext(context.Context) RandomUuid7MapOutput
}

type RandomUuid7Map map[string]RandomUuid7Input

func (RandomUuid7Map) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RandomUuid7)(nil)).Elem()
}

func (i RandomUuid7Map) ToRandomUuid7MapOutput() RandomUuid7MapOutput {
	return i.ToRandomUuid7MapOutputWithContext(context.Background())
}

func (i RandomUuid7Map) ToRandomUuid7MapOutputWithContext(ctx context.Context) RandomUuid7MapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RandomUuid7MapOutput)
}

type RandomUuid7Output struct{ *pulumi.OutputState }

func (RandomUuid7Output) ElementType() reflect.Type {
	return reflect.TypeOf((**RandomUuid7)(nil)).Elem()
}

func (o RandomUuid7Output) ToRandomUuid7Output() RandomUuid7Output {
	return o
}

func (o RandomUuid7Output) ToRandomUuid7OutputWithContext(ctx context.Context) RandomUuid7Output {
	return o
}

// Arbitrary map of values that, when changed, will trigger recreation of resource. See the main provider documentation for more information.
func (o RandomUuid7Output) Keepers() pulumi.StringMapOutput {
	return o.ApplyT(func(v *RandomUuid7) pulumi.StringMapOutput { return v.Keepers }).(pulumi.StringMapOutput)
}

// The generated uuid presented in string format.
func (o RandomUuid7Output) Result() pulumi.StringOutput {
	return o.ApplyT(func(v *RandomUuid7) pulumi.StringOutput { return v.Result }).(pulumi.StringOutput)
}

type RandomUuid7ArrayOutput struct{ *pulumi.OutputState }

func (RandomUuid7ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*RandomUuid7)(nil)).Elem()
}

func (o RandomUuid7ArrayOutput) ToRandomUuid7ArrayOutput() RandomUuid7ArrayOutput {
	return o
}

func (o RandomUuid7ArrayOutput) ToRandomUuid7ArrayOutputWithContext(ctx context.Context) RandomUuid7ArrayOutput {
	return o
}

func (o RandomUuid7ArrayOutput) Index(i pulumi.IntInput) RandomUuid7Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *RandomUuid7 {
		return vs[0].([]*RandomUuid7)[vs[1].(int)]
	}).(RandomUuid7Output)
}

type RandomUuid7MapOutput struct{ *pulumi.OutputState }

func (RandomUuid7MapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*RandomUuid7)(nil)).Elem()
}

func (o RandomUuid7MapOutput) ToRandomUuid7MapOutput() RandomUuid7MapOutput {
	return o
}

func (o RandomUuid7MapOutput) ToRandomUuid7MapOutputWithContext(ctx context.Context) RandomUuid7MapOutput {
	return o
}

func (o RandomUuid7MapOutput) MapIndex(k pulumi.StringInput) RandomUuid7Output {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *RandomUuid7 {
		return vs[0].(map[string]*RandomUuid7)[vs[1].(string)]
	}).(RandomUuid7Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RandomUuid7Input)(nil)).Elem(), &RandomUuid7{})
	pulumi.RegisterInputType(reflect.TypeOf((*RandomUuid7ArrayInput)(nil)).Elem(), RandomUuid7Array{})
	pulumi.RegisterInputType(reflect.TypeOf((*RandomUuid7MapInput)(nil)).Elem(), RandomUuid7Map{})
	pulumi.RegisterOutputType(RandomUuid7Output{})
	pulumi.RegisterOutputType(RandomUuid7ArrayOutput{})
	pulumi.RegisterOutputType(RandomUuid7MapOutput{})
}
