# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import pulumi
import pulumi.runtime
from . import utilities, tables

class RandomString(pulumi.CustomResource):
    """
    The resource `random_string` generates a random permutation of alphanumeric
    characters and optionally special characters.
    
    This resource *does* use a cryptographic random number generator.
    """
    def __init__(__self__, __name__, __opts__=None, keepers=None, length=None, lower=None, min_lower=None, min_numeric=None, min_special=None, min_upper=None, number=None, override_special=None, special=None, upper=None):
        """Create a RandomString resource with the given unique name, props, and options."""
        if not __name__:
            raise TypeError('Missing resource name argument (for URN creation)')
        if not isinstance(__name__, str):
            raise TypeError('Expected resource name to be a string')
        if __opts__ and not isinstance(__opts__, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')

        __props__ = dict()

        __props__['keepers'] = keepers

        if not length:
            raise TypeError('Missing required property length')
        __props__['length'] = length

        __props__['lower'] = lower

        __props__['min_lower'] = min_lower

        __props__['min_numeric'] = min_numeric

        __props__['min_special'] = min_special

        __props__['min_upper'] = min_upper

        __props__['number'] = number

        __props__['override_special'] = override_special

        __props__['special'] = special

        __props__['upper'] = upper

        __props__['result'] = None

        super(RandomString, __self__).__init__(
            'random:index/randomString:RandomString',
            __name__,
            __props__,
            __opts__)


    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

