// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The resource `random_integer` generates random values from a given range, described by the `min` and `max` attributes of a given resource.
 * 
 * This resource can be used in conjunction with resources that have
 * the `create_before_destroy` lifecycle flag set, to avoid conflicts with
 * unique names during the brief period where both the old and new resources
 * exist concurrently.
 */
export class RandomInteger extends pulumi.CustomResource {
    /**
     * Get an existing RandomInteger resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RandomIntegerState, opts?: pulumi.CustomResourceOptions): RandomInteger {
        return new RandomInteger(name, <any>state, { ...opts, id: id });
    }

    /**
     * Arbitrary map of values that, when changed, will
     * trigger a new id to be generated. See
     * the main provider documentation for more information.
     */
    public readonly keepers: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * The maximum inclusive value of the range.
     */
    public readonly max: pulumi.Output<number>;
    /**
     * The minimum inclusive value of the range.
     */
    public readonly min: pulumi.Output<number>;
    /**
     * (int) The random Integer result.
     */
    public /*out*/ readonly result: pulumi.Output<number>;
    /**
     * A custom seed to always produce the same value.
     */
    public readonly seed: pulumi.Output<string | undefined>;

    /**
     * Create a RandomInteger resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RandomIntegerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RandomIntegerArgs | RandomIntegerState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state: RandomIntegerState = argsOrState as RandomIntegerState | undefined;
            inputs["keepers"] = state ? state.keepers : undefined;
            inputs["max"] = state ? state.max : undefined;
            inputs["min"] = state ? state.min : undefined;
            inputs["result"] = state ? state.result : undefined;
            inputs["seed"] = state ? state.seed : undefined;
        } else {
            const args = argsOrState as RandomIntegerArgs | undefined;
            if (!args || args.max === undefined) {
                throw new Error("Missing required property 'max'");
            }
            if (!args || args.min === undefined) {
                throw new Error("Missing required property 'min'");
            }
            inputs["keepers"] = args ? args.keepers : undefined;
            inputs["max"] = args ? args.max : undefined;
            inputs["min"] = args ? args.min : undefined;
            inputs["seed"] = args ? args.seed : undefined;
            inputs["result"] = undefined /*out*/;
        }
        super("random:index/randomInteger:RandomInteger", name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RandomInteger resources.
 */
export interface RandomIntegerState {
    /**
     * Arbitrary map of values that, when changed, will
     * trigger a new id to be generated. See
     * the main provider documentation for more information.
     */
    readonly keepers?: pulumi.Input<{[key: string]: any}>;
    /**
     * The maximum inclusive value of the range.
     */
    readonly max?: pulumi.Input<number>;
    /**
     * The minimum inclusive value of the range.
     */
    readonly min?: pulumi.Input<number>;
    /**
     * (int) The random Integer result.
     */
    readonly result?: pulumi.Input<number>;
    /**
     * A custom seed to always produce the same value.
     */
    readonly seed?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RandomInteger resource.
 */
export interface RandomIntegerArgs {
    /**
     * Arbitrary map of values that, when changed, will
     * trigger a new id to be generated. See
     * the main provider documentation for more information.
     */
    readonly keepers?: pulumi.Input<{[key: string]: any}>;
    /**
     * The maximum inclusive value of the range.
     */
    readonly max: pulumi.Input<number>;
    /**
     * The minimum inclusive value of the range.
     */
    readonly min: pulumi.Input<number>;
    /**
     * A custom seed to always produce the same value.
     */
    readonly seed?: pulumi.Input<string>;
}
